### ISSUE TITLE
Orthographical Errors in plain sight of Layer 8

### ISSUE THREAD

**Issue by boideltier** [erdmaschine/bot#22]
There is an orthographical error in the suggestions for the "name" input-field for the `/fallacy`-command. For details, see picture attached. 
![Screenshot_20231217-104122~2.png](https://github.com/erdmaschine/bot/assets/44578048/53519af7-4487-4e40-8905-ce0c5e65205e)

**Comment by ApoY2k** [comment]
I taught you the skills to fix this yourself. Use them. Looking forward to your PR.
